import { initializeApp, getApps } from 'firebase/app';
import { getAuth, GoogleAuthProvider, signInWithPopup } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

// Note: firebase-applet-config.json is generated by set_up_firebase.
// We use a safe check to prevent crashes if it doesn't exist.
// @ts-ignore
import firebaseConfig from '../../firebase-applet-config.json';

export function getFirebaseApp() {
  if (!firebaseConfig || !(firebaseConfig as any).apiKey) return null;
  if (getApps().length > 0) return getApps()[0];
  return initializeApp(firebaseConfig);
}

export function getFbAuth() {
  const app = getFirebaseApp();
  if (!app) return null;
  return getAuth(app);
}

export function getDb() {
  const app = getFirebaseApp();
  if (!app || !firebaseConfig) return null;
  return getFirestore(app, (firebaseConfig as any).firestoreDatabaseId);
}

export const googleProvider = new GoogleAuthProvider();

export async function signInWithGoogle() {
  const auth = getFbAuth();
  if (!auth) throw new Error('Firebase Auth not initialized');
  return signInWithPopup(auth, googleProvider);
}

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
  }
}

export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const auth = getFbAuth();
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth?.currentUser?.uid,
      email: auth?.currentUser?.email,
      emailVerified: auth?.currentUser?.emailVerified,
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}
